# Generated by Django 5.1.1 on 2024-09-24 15:48

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.CharField(max_length=300)),
                ('avatar', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('comment', models.CharField(max_length=300)),
                ('comment_imgs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('brand', models.CharField(max_length=300)),
            ],
        ),
    ]
